package com.yana.privateNetTest.LocalMachine.message.categoly;

public enum LocalActionCategory {
	REQ_REGIST_ME,
	HANDSHAKE_COMLETE,
	COMMON_COMMUNICATE,
	DISPLAY_ACTIVE_USER,
	ACK_HELLO_MYNAMEIS,
	REGIST_CONNECTED_ACTIVE_USER,
	ACK_LIST_ALL,
	DISPLAY_RESPONSE_LIST_ALL,
	ACK_MY_DATA,
	NOTIFY_REQESUT_FAILED,
	COLLECT_ACK_DATA,
	NONE
}
